import type { GrammarEntry } from '../core/types';

/** Chapter 1 grammar. Original example sentences and exercises (not official JLPT material). */
export const GRAMMAR: GrammarEntry[] = [
  {
    id: 'wakedewanai',
    pattern: '～わけではない',
    meaning: "it's not (necessarily) that ~; it doesn't mean that ~",
    formation: 'plain form (な-adj：～な／である) + わけではない',
    explanation:
      'Partially denies a conclusion the listener might draw. It does not say the statement is false or impossible — it says "that is not the whole story".',
    nuance: 'Soft, explanatory. Often follows からといって (“just because …”). Casual: わけじゃない.',
    mistakes: 'Not the same as わけがない (“there is no way”). わけではない corrects an assumption; わけがない rejects a possibility completely.',
    examples: [
      { jp: '日本語が難しいからといって、勉強が嫌いなわけではない。', en: "Just because Japanese is hard doesn't mean I dislike studying it." },
      { jp: '全部わかったわけではないけど、だいたい理解できた。', en: "It's not that I understood everything, but I got the gist." },
    ],
    similar: ['wakeganai', 'wakeniwaikanai'],
    exercises: [
      {
        sentence: '毎日カフェに来ているが、コーヒーが特に好きな＿＿。店の雰囲気が好きなのだ。',
        en: "I come to the café every day, but it isn't that I especially like coffee. I like the atmosphere.",
        options: [{ text: 'わけではない', grammar: 'wakedewanai' }, { text: 'わけがない', grammar: 'wakeganai' }, { text: 'わけにはいかない', grammar: 'wakeniwaikanai' }, { text: 'に違いない', grammar: 'nichigainai' }],
        answer: 0,
        why: 'The speaker corrects a likely assumption (“you must love coffee”) → partial denial: わけではない.',
      },
      {
        sentence: '高い料理がいつもおいしい＿＿。',
        en: "Expensive food isn't always delicious.",
        options: [{ text: 'わけではない', grammar: 'wakedewanai' }, { text: 'わけにはいかない', grammar: 'wakeniwaikanai' }, { text: 'ついでに', grammar: 'tsuideni' }, { text: 'からこそ', grammar: 'karakoso' }],
        answer: 0,
        why: 'いつも～わけではない = “not always”. It denies a generalisation, not every case.',
      },
    ],
    level: 'N3',
    chapter: 1,
  },
  {
    id: 'wakeganai',
    pattern: '～わけがない',
    meaning: "there's no way that ~; ~ can't possibly be",
    formation: 'plain form (な-adj：～な) + わけがない',
    explanation: 'Strongly rejects a possibility based on the speaker’s reasoning. Similar to はずがない but more emotional / subjective.',
    nuance: 'Strong, often emotional. Casual: わけない.',
    mistakes: 'Do not use it to soften a statement — that is わけではない.',
    examples: [
      { jp: 'あんなに練習したんだから、失敗するわけがない。', en: "After practising that much, there's no way I'll fail." },
      { jp: '一日で漢字を千字覚えられるわけがない。', en: "There's no way you can learn a thousand kanji in one day." },
    ],
    similar: ['wakedewanai', 'nichigainai'],
    exercises: [
      {
        sentence: 'あの正直なハルトくんが、うそをつく＿＿。',
        en: "There's no way honest Haruto would lie.",
        options: [{ text: 'わけがない', grammar: 'wakeganai' }, { text: 'わけではない', grammar: 'wakedewanai' }, { text: 'わけにはいかない', grammar: 'wakeniwaikanai' }, { text: 'せいで', grammar: 'seide' }],
        answer: 0,
        why: 'The speaker completely rejects the possibility → わけがない.',
      },
      {
        sentence: 'こんなに暗い森で、小さな足跡が見える＿＿よ。明日の朝にしよう。',
        en: "There's no way we'll see small footprints in a forest this dark. Let's do it tomorrow morning.",
        options: [{ text: 'わけがない', grammar: 'wakeganai' }, { text: 'に違いない', grammar: 'nichigainai' }, { text: 'わけではない', grammar: 'wakedewanai' }, { text: 'ばかりでなく', grammar: 'bakaridenaku' }],
        answer: 0,
        why: 'Logical impossibility judged by the speaker → わけがない.',
      },
    ],
    level: 'N2',
    chapter: 1,
  },
  {
    id: 'wakeniwaikanai',
    pattern: '～わけにはいかない',
    meaning: "can't (afford to) ~ (for social / moral reasons)",
    formation: 'dictionary form + わけにはいかない ／ ない-form + わけにはいかない (= must)',
    explanation: 'Something is physically possible, but circumstances, duty or common sense make it unacceptable.',
    nuance: 'Expresses obligation or restraint. ～ないわけにはいかない = “I have no choice but to ~”.',
    mistakes: 'Not for inability (use できない / られない). You CAN do it — you just shouldn’t.',
    examples: [
      { jp: '大事な約束があるので、今日は休むわけにはいかない。', en: "I have an important appointment, so I can't take today off." },
      { jp: '先輩に頼まれたら、手伝わないわけにはいかない。', en: 'If a senior colleague asks, I have to help.' },
    ],
    similar: ['wakedewanai', 'wakeganai'],
    exercises: [
      {
        sentence: '楓さんに頼まれたのだから、途中でやめる＿＿。',
        en: "Kaede asked me, so I can't just quit halfway.",
        options: [{ text: 'わけにはいかない', grammar: 'wakeniwaikanai' }, { text: 'わけがない', grammar: 'wakeganai' }, { text: 'わけではない', grammar: 'wakedewanai' }, { text: 'かねない', grammar: 'kanenai' }],
        answer: 0,
        why: 'Quitting is possible but socially unacceptable → わけにはいかない.',
      },
      {
        sentence: '明日は試験だから、今夜は勉強しない＿＿。',
        en: "The exam is tomorrow, so I have to study tonight.",
        options: [{ text: 'わけにはいかない', grammar: 'wakeniwaikanai' }, { text: 'わけではない', grammar: 'wakedewanai' }, { text: 'わけがない', grammar: 'wakeganai' }, { text: 'っぱなし', grammar: 'ppanashi' }],
        answer: 0,
        why: 'ない-form + わけにはいかない = “cannot not do” → must.',
      },
    ],
    level: 'N2',
    chapter: 1,
  },
  {
    id: 'nichigainai',
    pattern: '～に違いない',
    meaning: 'must be ~; surely ~ (strong conviction)',
    formation: 'plain form (な-adj／noun without だ) + に違いない',
    explanation: 'The speaker is convinced based on evidence or intuition. Mostly written or formal; in conversation きっと～だ is common.',
    nuance: 'More subjective than はずだ (which is based on logic or facts).',
    mistakes: 'Don’t add だ before it: ×本当だに違いない → ○本当に違いない.',
    examples: [
      { jp: '電気がついている。誰かいるに違いない。', en: 'The lights are on. Someone must be there.' },
      { jp: 'この手紙を書いたのは、町の人に違いない。', en: 'The person who wrote this letter must be someone from town.' },
    ],
    similar: ['wakeganai', 'kanenai'],
    exercises: [
      {
        sentence: '足跡がまだ新しい。この近くに言霊がいる＿＿。',
        en: 'The footprints are still fresh. There must be a Kotodama nearby.',
        options: [{ text: 'に違いない', grammar: 'nichigainai' }, { text: 'わけではない', grammar: 'wakedewanai' }, { text: 'わけにはいかない', grammar: 'wakeniwaikanai' }, { text: 'をきっかけに', grammar: 'wokikkakeni' }],
        answer: 0,
        why: 'A conclusion drawn from evidence (fresh footprints) → に違いない.',
      },
      {
        sentence: 'あんなにうれしそうな顔をしているから、試験に合格した＿＿。',
        en: 'With that happy face, she must have passed the exam.',
        options: [{ text: 'に違いない', grammar: 'nichigainai' }, { text: 'わけがない', grammar: 'wakeganai' }, { text: 'かねない', grammar: 'kanenai' }, { text: 'せいで', grammar: 'seide' }],
        answer: 0,
        why: 'Strong positive guess based on what the speaker sees → に違いない.',
      },
    ],
    level: 'N2',
    chapter: 1,
  },
  {
    id: 'kanenai',
    pattern: '～かねない',
    meaning: 'could well ~; might ~ (something bad)',
    formation: 'ます-stem + かねない',
    explanation: 'Warns that an undesirable result is possible. Used only for negative outcomes.',
    nuance: 'Formal / written. Do not use for good results (×合格しかねない).',
    mistakes: 'Looks negative (～ない) but the meaning is positive possibility: “it may happen”.',
    examples: [
      { jp: 'このまま放っておくと、大きな事故になりかねない。', en: 'If we leave it like this, it could turn into a serious accident.' },
      { jp: '寝不足が続くと、体を壊しかねない。', en: 'If you keep not sleeping enough, you could ruin your health.' },
    ],
    similar: ['nichigainai'],
    exercises: [
      {
        sentence: '言葉が消える現象をこのままにしておくと、町中が混乱し＿＿。',
        en: 'If we leave the vanishing-words phenomenon alone, the whole town could fall into chaos.',
        options: [{ text: 'かねない', grammar: 'kanenai' }, { text: 'に違いない', grammar: 'nichigainai' }, { text: 'わけではない', grammar: 'wakedewanai' }, { text: 'からこそ', grammar: 'karakoso' }],
        answer: 0,
        why: 'Warning about a possible bad outcome; attaches to the ます-stem (混乱し) → かねない.',
      },
    ],
    level: 'N2',
    chapter: 1,
  },
  {
    id: 'wokikkakeni',
    pattern: '～をきっかけに',
    meaning: 'taking ~ as an opportunity; triggered by ~',
    formation: 'noun + をきっかけに（して）／ ～たのをきっかけに',
    explanation: 'Marks the event that triggered a change or a new start.',
    nuance: 'Neutral. Similar: を契機に (more formal).',
    mistakes: 'The part after it must describe a change or start, not a one-off action unrelated to the trigger.',
    examples: [
      { jp: '日本への引っ越しをきっかけに、日記を書き始めた。', en: 'Moving to Japan prompted me to start keeping a diary.' },
      { jp: 'アニメを見たのをきっかけに、日本語に興味を持った。', en: 'Watching anime got me interested in Japanese.' },
    ],
    similar: ['karakoso'],
    exercises: [
      {
        sentence: 'あの手紙＿＿、私は町の謎を調べ始めた。',
        en: 'That letter was what got me to start investigating the town’s mystery.',
        options: [{ text: 'をきっかけに', grammar: 'wokikkakeni' }, { text: 'ついでに', grammar: 'tsuideni' }, { text: 'につれて', grammar: 'nitsurete' }, { text: 'せいで', grammar: 'seide' }],
        answer: 0,
        why: 'The letter triggered a new beginning → をきっかけに.',
      },
    ],
    level: 'N2',
    chapter: 1,
  },
  {
    id: 'karakoso',
    pattern: '～からこそ',
    meaning: 'precisely because ~',
    formation: 'plain form + からこそ',
    explanation: 'Emphasises that the reason is THE reason — often a positive or surprising one.',
    nuance: 'Emphatic. Typically not used with negative excuses.',
    mistakes: 'Do not use when the result is a complaint; せいで fits negative causes better.',
    examples: [
      { jp: '友達だからこそ、本当のことを言うんだ。', en: "It's precisely because we're friends that I'm telling you the truth." },
      { jp: '難しいからこそ、面白い。', en: "It's interesting precisely because it's difficult." },
    ],
    similar: ['seide', 'wokikkakeni'],
    exercises: [
      {
        sentence: '言葉を大切にするあなただ＿＿、この仕事を頼みたいの。',
        en: 'It is exactly because you treasure words that I want to ask you this.',
        options: [{ text: 'からこそ', grammar: 'karakoso' }, { text: 'せいで', grammar: 'seide' }, { text: 'わけがない', grammar: 'wakeganai' }, { text: 'ばかりでなく', grammar: 'bakaridenaku' }],
        answer: 0,
        why: 'Emphasised, positive reason → からこそ.',
      },
    ],
    level: 'N2',
    chapter: 1,
  },
  {
    id: 'seide',
    pattern: '～せいで',
    meaning: 'because of ~ (blame, negative result)',
    formation: 'plain form (な-adj：～な／noun：～の) + せいで',
    explanation: 'Gives a cause for a bad result, often with a sense of blame. Positive counterpart: おかげで.',
    nuance: 'せいか = “perhaps because”.',
    mistakes: 'Using せいで for a good result sounds sarcastic.',
    examples: [
      { jp: '雨のせいで、試合が中止になった。', en: 'The match was cancelled because of the rain.' },
      { jp: '寝坊したせいで、電車に乗り遅れた。', en: 'Because I overslept, I missed the train.' },
    ],
    similar: ['karakoso'],
    exercises: [
      {
        sentence: '信号トラブルの＿＿、三十分も待たされた。',
        en: 'Because of the signal trouble, I had to wait thirty minutes.',
        options: [{ text: 'せいで', grammar: 'seide' }, { text: 'からこそ', grammar: 'karakoso' }, { text: 'おかげで' }, { text: 'ついでに', grammar: 'tsuideni' }],
        answer: 0,
        why: 'A negative result caused by something (blame) → せいで. おかげで would sound sarcastic.',
      },
    ],
    level: 'N3',
    chapter: 1,
  },
  {
    id: 'tsuideni',
    pattern: '～ついでに',
    meaning: 'while (doing) ~; on the way / at the same time',
    formation: 'dictionary form／た-form／noun + の + ついでに',
    explanation: 'Doing an extra thing taking advantage of an opportunity created by the main action.',
    nuance: 'Casual and everyday. The main action comes first; the extra action follows.',
    mistakes: 'Not for two equal goals done simultaneously (use ながら for parallel actions).',
    examples: [
      { jp: '買い物のついでに、郵便局に寄った。', en: 'While I was out shopping, I dropped by the post office.' },
      { jp: '駅に行くついでに、手紙を出してくれる？', en: "Since you're going to the station anyway, could you post this letter?" },
    ],
    similar: ['ueni'],
    exercises: [
      {
        sentence: 'コンビニに行く＿＿、ハルトくんの様子も見てきてくれる？',
        en: "Since you're going to the convenience store, could you check on Haruto too?",
        options: [{ text: 'ついでに', grammar: 'tsuideni' }, { text: 'うえに', grammar: 'ueni' }, { text: 'につれて', grammar: 'nitsurete' }, { text: 'わけではない', grammar: 'wakedewanai' }],
        answer: 0,
        why: 'Extra errand piggy-backing on a main trip → ついでに.',
      },
    ],
    level: 'N2',
    chapter: 1,
  },
  {
    id: 'ueni',
    pattern: '～うえに',
    meaning: 'on top of ~; besides ~',
    formation: 'plain form (な-adj：～な／noun：～である) + うえに',
    explanation: 'Adds a second fact of the same direction (good + good, bad + bad).',
    nuance: 'Written / formal; casual equivalent: ～し、それに.',
    mistakes: 'Both clauses must point the same way. ×安いうえに、まずい (mixed) is unnatural.',
    examples: [
      { jp: 'この店は安いうえに、量も多い。', en: 'This place is cheap, and on top of that the portions are big.' },
      { jp: '道に迷ったうえに、雨まで降ってきた。', en: 'I got lost, and on top of that it started to rain.' },
    ],
    similar: ['bakaridenaku', 'tsuideni'],
    exercises: [
      {
        sentence: '楓さんのカフェは、コーヒーがおいしい＿＿、ケーキも手作りだ。',
        en: "Kaede's café has great coffee, and on top of that the cakes are homemade.",
        options: [{ text: 'うえに', grammar: 'ueni' }, { text: 'せいで', grammar: 'seide' }, { text: 'わけがない', grammar: 'wakeganai' }, { text: 'につれて', grammar: 'nitsurete' }],
        answer: 0,
        why: 'Adds a second positive point → うえに.',
      },
    ],
    level: 'N2',
    chapter: 1,
  },
  {
    id: 'bakaridenaku',
    pattern: '～ばかりでなく',
    meaning: 'not only ~ (but also)',
    formation: 'plain form (な-adj：～な／noun) + ばかりでなく、～も',
    explanation: 'Introduces a first item and signals that the scope is wider. Usually followed by も／まで.',
    nuance: 'Slightly formal; casual: ～だけじゃなくて.',
    mistakes: 'Don’t confuse with ～てばかりいる (“do nothing but ~”).',
    examples: [
      { jp: 'この現象は町の人ばかりでなく、動物にも影響している。', en: 'This phenomenon affects not only the townspeople but animals too.' },
      { jp: '彼女は英語ばかりでなく、ドイツ語も話せる。', en: 'She speaks not only English but German as well.' },
    ],
    similar: ['ueni'],
    exercises: [
      {
        sentence: '言葉が消える現象は、日野森＿＿、となりの町でも起きているらしい。',
        en: 'Apparently the vanishing-words phenomenon is happening not only in Hinomori but in the neighbouring town too.',
        options: [{ text: 'ばかりでなく', grammar: 'bakaridenaku' }, { text: 'のせいで', grammar: 'seide' }, { text: 'からこそ', grammar: 'karakoso' }, { text: 'につれて', grammar: 'nitsurete' }],
        answer: 0,
        why: '“not only X, but also (でも) Y” → ばかりでなく.',
      },
    ],
    level: 'N2',
    chapter: 1,
  },
  {
    id: 'nitsurete',
    pattern: '～につれて',
    meaning: 'as ~ (changes), … (also changes)',
    formation: 'dictionary form／noun + につれて',
    explanation: 'Proportional change: as one thing progresses, another changes along with it.',
    nuance: 'Both parts must describe gradual change. Similar: ～にしたがって, ～とともに.',
    mistakes: 'Not for a single one-time event (×ドアを開けるにつれて).',
    examples: [
      { jp: '時間がたつにつれて、記憶が薄れていく。', en: 'As time passes, memories fade.' },
      { jp: '森の奥へ進むにつれて、空気が冷たくなった。', en: 'The deeper we went into the forest, the colder the air got.' },
    ],
    similar: ['ueni'],
    exercises: [
      {
        sentence: '日本での生活に慣れる＿＿、日本語で考えることが増えてきた。',
        en: 'As I got used to life in Japan, I started thinking in Japanese more often.',
        options: [{ text: 'につれて', grammar: 'nitsurete' }, { text: 'ついでに', grammar: 'tsuideni' }, { text: 'うえに', grammar: 'ueni' }, { text: 'わけにはいかない', grammar: 'wakeniwaikanai' }],
        answer: 0,
        why: 'Two gradual, linked changes → につれて.',
      },
    ],
    level: 'N2',
    chapter: 1,
  },
  {
    id: 'ppanashi',
    pattern: '～っぱなし',
    meaning: 'leaving ~ as it is; continuously ~',
    formation: 'ます-stem + っぱなし',
    explanation: 'An action was done and the resulting state was left (often carelessly), or something continues for a long time.',
    nuance: 'Usually critical/negative. 出しっぱなし, つけっぱなし, 立ちっぱなし are very common.',
    mistakes: 'Attach to the ます-stem: ○開けっぱなし ×開けるっぱなし.',
    examples: [
      { jp: '電気をつけっぱなしで寝てしまった。', en: 'I fell asleep with the light left on.' },
      { jp: '今日は一日中立ちっぱなしで、足が痛い。', en: "I've been standing all day today and my feet hurt." },
    ],
    similar: [],
    exercises: [
      {
        sentence: '窓を開け＿＿にしていたら、部屋に葉っぱが入ってきた。',
        en: 'I left the window open and leaves blew into the room.',
        options: [{ text: 'っぱなし', grammar: 'ppanashi' }, { text: 'ついで', grammar: 'tsuideni' }, { text: 'かねない', grammar: 'kanenai' }, { text: 'うえ', grammar: 'ueni' }],
        answer: 0,
        why: 'A state carelessly left as it is → ます-stem + っぱなし.',
      },
    ],
    level: 'N2',
    chapter: 1,
  },
  {
    id: 'monoda',
    pattern: '～ものだ',
    meaning: '(nostalgia) used to ~; (general truth) that’s how ~ is',
    formation: 'た-form + ものだ (past habit) ／ dictionary form + ものだ (general truth / advice)',
    explanation: 'With た-form: fond recollection of a past habit. With dictionary form: a general truth or what one naturally should do.',
    nuance: 'Casual: もんだ. ～ものではない = “one shouldn’t”.',
    mistakes: 'Not for a single past event: ×昨日カフェに行ったものだ.',
    examples: [
      { jp: '子供の頃は、よくこの川で遊んだものだ。', en: 'When I was a child, I often used to play in this river.' },
      { jp: '人の記憶は、意外と曖昧なものだ。', en: 'Human memory is surprisingly vague — that’s just how it is.' },
    ],
    similar: [],
    exercises: [
      {
        sentence: '学生の頃は、毎晩遅くまで友達と話した＿＿なあ。',
        en: 'Back in my student days, I used to talk with friends late into the night.',
        options: [{ text: 'ものだ', grammar: 'monoda' }, { text: 'に違いない', grammar: 'nichigainai' }, { text: 'わけだ' }, { text: 'っぱなしだ', grammar: 'ppanashi' }],
        answer: 0,
        why: 'Nostalgic past habit (た-form + ものだ).',
      },
    ],
    level: 'N2',
    chapter: 1,
  },
];

export const GRAMMAR_BY_ID: Record<string, GrammarEntry> = Object.fromEntries(GRAMMAR.map((g) => [g.id, g]));
