/* generated by tools/build_rooms.py — do not edit */
import type { MapObject } from './maps';

export const ROOMS_GEN: Record<string, { tiles: string[]; image: string; objects: MapObject[] }> = {
  "konbini": {
    "tiles": [
      "WWWWWWWWWWWWWWW",
      "WWWWWWWWWWWWWWW",
      "fffffffffffffff",
      "fffffffffffffff",
      "ffffffffffccccc",
      "fffffffffffffff",
      "fffffffffffffff",
      "fffffffffffffff",
      "fffffffffffffff",
      "fffffffffffffff",
      "fffffffffffffff",
      "WWWWWWWDWWWWWWW"
    ],
    "objects": [
      {
        "id": "konbini_fridge1",
        "sprite": "fu_konbini_fridge1",
        "x": 0,
        "y": 2,
        "w": 1,
        "h": 1,
        "script": "konbini_fridge"
      },
      {
        "id": "konbini_fridge2",
        "sprite": "fu_konbini_fridge2",
        "x": 1,
        "y": 2,
        "w": 1,
        "h": 1,
        "script": "konbini_fridge"
      },
      {
        "id": "konbini_fridge3",
        "sprite": "fu_konbini_fridge3",
        "x": 2,
        "y": 2,
        "w": 1,
        "h": 1,
        "script": "konbini_fridge"
      },
      {
        "id": "konbini_fridge4",
        "sprite": "fu_konbini_fridge4",
        "x": 3,
        "y": 2,
        "w": 1,
        "h": 1,
        "script": "konbini_fridge"
      },
      {
        "id": "konbini_bento1",
        "sprite": "fu_konbini_bento1",
        "x": 4,
        "y": 2,
        "w": 2,
        "h": 1,
        "script": "konbini_bento"
      },
      {
        "id": "konbini_bento2",
        "sprite": "fu_konbini_bento2",
        "x": 6,
        "y": 2,
        "w": 2,
        "h": 1,
        "script": "konbini_bento"
      },
      {
        "id": "konbini_coffee",
        "sprite": "fu_konbini_coffee",
        "x": 10,
        "y": 2,
        "w": 2,
        "h": 1,
        "script": "konbini_coffee"
      },
      {
        "id": "konbini_hotsnack",
        "sprite": "fu_konbini_hotsnack",
        "x": 12,
        "y": 2,
        "w": 1,
        "h": 1,
        "script": "konbini_counter"
      },
      {
        "id": "konbini_bakery",
        "sprite": "fu_konbini_bakery",
        "x": 13,
        "y": 2,
        "w": 2,
        "h": 1,
        "script": "konbini_counter"
      },
      {
        "id": "konbini_counter",
        "sprite": "fu_konbini_counter",
        "x": 10,
        "y": 4,
        "w": 5,
        "h": 1,
        "script": "konbini_counter"
      },
      {
        "id": "konbini_shelf1",
        "sprite": "fu_konbini_shelf1",
        "x": 1,
        "y": 5,
        "w": 3,
        "h": 1,
        "script": "konbini_shelf"
      },
      {
        "id": "konbini_shelf2",
        "sprite": "fu_konbini_shelf2",
        "x": 5,
        "y": 5,
        "w": 2,
        "h": 1,
        "script": "konbini_shelf"
      },
      {
        "id": "konbini_shelf3",
        "sprite": "fu_konbini_shelf3",
        "x": 1,
        "y": 8,
        "w": 2,
        "h": 1,
        "script": "konbini_shelf"
      },
      {
        "id": "konbini_shelf4",
        "sprite": "fu_konbini_shelf4",
        "x": 3,
        "y": 8,
        "w": 1,
        "h": 1,
        "script": "konbini_shelf"
      },
      {
        "id": "konbini_shelf5",
        "sprite": "fu_konbini_shelf5",
        "x": 5,
        "y": 8,
        "w": 1,
        "h": 1,
        "script": "konbini_shelf"
      },
      {
        "id": "konbini_shelf6",
        "sprite": "fu_konbini_shelf6",
        "x": 6,
        "y": 8,
        "w": 1,
        "h": 1,
        "script": "konbini_shelf"
      },
      {
        "id": "konbini_ice",
        "sprite": "fu_konbini_ice",
        "x": 8,
        "y": 7,
        "w": 2,
        "h": 1,
        "script": "konbini_ice"
      },
      {
        "id": "konbini_magazines",
        "sprite": "fu_konbini_magazines",
        "x": 14,
        "y": 7,
        "w": 1,
        "h": 1,
        "script": "konbini_magazines"
      },
      {
        "id": "konbini_atm",
        "sprite": "fu_konbini_atm",
        "x": 14,
        "y": 9,
        "w": 1,
        "h": 1,
        "script": "konbini_atm"
      },
      {
        "id": "konbini_bins",
        "sprite": "fu_konbini_bins",
        "x": 11,
        "y": 10,
        "w": 2,
        "h": 1,
        "script": "konbini_trash"
      },
      {
        "id": "konbini_baskets",
        "sprite": "fu_konbini_baskets",
        "x": 5,
        "y": 10,
        "w": 1,
        "h": 1,
        "script": "konbini_baskets"
      }
    ],
    "image": "room2_konbini"
  },
  "cafe": {
    "tiles": [
      "WWWWWWWWWWWWW",
      "WWWWWWWWWWWWW",
      "fffffffffffff",
      "cccccccffffff",
      "fffffffffffff",
      "fffffffffffff",
      "fffffffffffff",
      "fffffffffffff",
      "fffffffffffff",
      "fffffffffffff",
      "fffffffffffff",
      "WWWWWWDWWWWWW"
    ],
    "objects": [
      {
        "id": "cafe_bar_back",
        "sprite": "fu_cafe_bar_back",
        "x": 0,
        "y": 0,
        "w": 0,
        "h": 0,
        "solid": false,
        "at": [
          112,
          89
        ]
      },
      {
        "id": "cafe_bar",
        "sprite": "fu_cafe_bar",
        "x": 0,
        "y": 3,
        "w": 7,
        "h": 1,
        "script": "cafe_counter"
      },
      {
        "id": "cafe_cupboard",
        "sprite": "fu_cafe_cupboard",
        "x": 8,
        "y": 2,
        "w": 2,
        "h": 1,
        "script": "cafe_shelf"
      },
      {
        "id": "cafe_fridge",
        "sprite": "fu_cafe_fridge",
        "x": 10,
        "y": 2,
        "w": 1,
        "h": 1,
        "script": "cafe_shelf"
      },
      {
        "id": "cafe_clock",
        "sprite": "fu_cafe_clock",
        "x": 11,
        "y": 2,
        "w": 1,
        "h": 1,
        "script": "cafe_clock"
      },
      {
        "id": "cafe_plant",
        "sprite": "fu_cafe_plant",
        "x": 12,
        "y": 2,
        "w": 1,
        "h": 1,
        "script": "plant"
      },
      {
        "id": "cafe_table",
        "sprite": "fu_cafe_table",
        "x": 1,
        "y": 6,
        "w": 2,
        "h": 1,
        "script": "cafe_table"
      },
      {
        "id": "cafe_table2",
        "sprite": "fu_cafe_table2",
        "x": 3,
        "y": 8,
        "w": 2,
        "h": 1,
        "script": "cafe_table"
      },
      {
        "id": "cafe_booth_l",
        "sprite": "fu_cafe_booth_l",
        "x": 8,
        "y": 6,
        "w": 1,
        "h": 1,
        "script": "cafe_table"
      },
      {
        "id": "cafe_booth_t",
        "sprite": "fu_cafe_booth_t",
        "x": 9,
        "y": 6,
        "w": 1,
        "h": 1,
        "script": "cafe_table"
      },
      {
        "id": "cafe_booth_r",
        "sprite": "fu_cafe_booth_r",
        "x": 10,
        "y": 6,
        "w": 1,
        "h": 1,
        "script": "cafe_table"
      },
      {
        "id": "cafe_sofa",
        "sprite": "fu_cafe_sofa",
        "x": 9,
        "y": 9,
        "w": 2,
        "h": 1,
        "script": "cafe_sofa"
      },
      {
        "id": "cafe_books",
        "sprite": "fu_cafe_books",
        "x": 0,
        "y": 8,
        "w": 1,
        "h": 1,
        "script": "cafe_books"
      },
      {
        "id": "cafe_sign",
        "sprite": "fu_cafe_sign",
        "x": 4,
        "y": 10,
        "w": 1,
        "h": 1,
        "script": "cafe_menu"
      },
      {
        "id": "cafe_plant2",
        "sprite": "fu_cafe_plant2",
        "x": 0,
        "y": 10,
        "w": 1,
        "h": 1,
        "script": "plant"
      },
      {
        "id": "cafe_plant3",
        "sprite": "fu_cafe_plant3",
        "x": 12,
        "y": 10,
        "w": 1,
        "h": 1,
        "script": "plant"
      }
    ],
    "image": "room2_cafe"
  },
  "apartment": {
    "tiles": [
      "WWWWWWWWWWWW",
      "WWWWWWWWWWWW",
      "ffffffffffff",
      "ffffffffffff",
      "ffffffffffff",
      "ffffffffffff",
      "ffffffffffff",
      "ffffffffffff",
      "ffffffffffff",
      "ffffffffffff",
      "ffffffffffff",
      "WWWWWDDWWWWW"
    ],
    "objects": [
      {
        "id": "apartment_bed",
        "sprite": "fu_apartment_bed",
        "x": 0,
        "y": 2,
        "w": 2,
        "h": 3,
        "script": "bed"
      },
      {
        "id": "apartment_nightstand",
        "sprite": "fu_apartment_nightstand",
        "x": 2,
        "y": 2,
        "w": 1,
        "h": 1,
        "script": "nightstand"
      },
      {
        "id": "apartment_desk",
        "sprite": "fu_apartment_desk",
        "x": 5,
        "y": 2,
        "w": 3,
        "h": 1,
        "script": "desk"
      },
      {
        "id": "apartment_shelf",
        "sprite": "fu_apartment_shelf",
        "x": 8,
        "y": 2,
        "w": 1,
        "h": 1,
        "script": "shelf"
      },
      {
        "id": "apartment_wardrobe",
        "sprite": "fu_apartment_wardrobe",
        "x": 9,
        "y": 2,
        "w": 2,
        "h": 1,
        "script": "wardrobe"
      },
      {
        "id": "apartment_plant",
        "sprite": "fu_apartment_plant",
        "x": 11,
        "y": 2,
        "w": 1,
        "h": 1,
        "script": "plant"
      },
      {
        "id": "apartment_tv",
        "sprite": "fu_apartment_tv",
        "x": 8,
        "y": 4,
        "w": 2,
        "h": 1,
        "script": "tv"
      },
      {
        "id": "apartment_kotatsu",
        "sprite": "fu_apartment_kotatsu",
        "x": 7,
        "y": 6,
        "w": 3,
        "h": 2,
        "script": "kotatsu"
      },
      {
        "id": "apartment_cushion_b",
        "sprite": "fu_apartment_cushion_b",
        "x": 6,
        "y": 7,
        "w": 1,
        "h": 1,
        "solid": false
      },
      {
        "id": "apartment_cushion_r",
        "sprite": "fu_apartment_cushion_r",
        "x": 10,
        "y": 7,
        "w": 1,
        "h": 1,
        "solid": false
      },
      {
        "id": "apartment_lamp",
        "sprite": "fu_apartment_lamp",
        "x": 11,
        "y": 5,
        "w": 1,
        "h": 1,
        "script": "floorlamp"
      },
      {
        "id": "apartment_mirror",
        "sprite": "fu_apartment_mirror",
        "x": 0,
        "y": 8,
        "w": 1,
        "h": 1,
        "script": "mirror_room"
      },
      {
        "id": "apartment_kitchen",
        "sprite": "fu_apartment_kitchen",
        "x": 0,
        "y": 10,
        "w": 3,
        "h": 1,
        "script": "kitchen"
      },
      {
        "id": "apartment_fridge",
        "sprite": "fu_apartment_fridge",
        "x": 3,
        "y": 10,
        "w": 1,
        "h": 1,
        "script": "fridge"
      },
      {
        "id": "apartment_shoes",
        "sprite": "fu_apartment_shoes",
        "x": 8,
        "y": 10,
        "w": 1,
        "h": 1,
        "script": "shoes"
      },
      {
        "id": "apartment_laundry",
        "sprite": "fu_apartment_laundry",
        "x": 0,
        "y": 6,
        "w": 1,
        "h": 1,
        "script": "laundry"
      },
      {
        "id": "apartment_plant2",
        "sprite": "fu_apartment_plant2",
        "x": 11,
        "y": 10,
        "w": 1,
        "h": 1,
        "script": "plant"
      }
    ],
    "image": "room2_apartment"
  }
};
