/* generated by tools/build_rooms.py — do not edit */
import type { MapObject } from './maps';

export const ROOMS_GEN: Record<string, { tiles: string[]; image: string; objects: MapObject[] }> = {
  "konbini": {
    "tiles": [
      "WWWWWWWWWWWWWWW",
      "WWWWWWWWWWWWWWW",
      "WWWWWWWWWWWWWWW",
      "WWWWWWWWWWWWWWW",
      "WWfffffffffccfW",
      "WWfffffffffccfW",
      "WWfffffffffccfW",
      "WWfffffffffccfW",
      "WWfffffffffccfW",
      "WWffffffffffWWW",
      "WWWWWWfffWWWWWW",
      "WWWWWWDDDWWWWWW"
    ],
    "objects": [
      {
        "id": "konbini_shelf1",
        "sprite": "fu_konbini_shelf1",
        "x": 3,
        "y": 5,
        "w": 3,
        "h": 1,
        "script": "konbini_shelf"
      },
      {
        "id": "konbini_shelf2",
        "sprite": "fu_konbini_shelf2",
        "x": 7,
        "y": 5,
        "w": 3,
        "h": 1,
        "script": "konbini_shelf"
      },
      {
        "id": "konbini_shelf3",
        "sprite": "fu_konbini_shelf3",
        "x": 3,
        "y": 7,
        "w": 3,
        "h": 1,
        "script": "konbini_shelf"
      },
      {
        "id": "konbini_shelf4",
        "sprite": "fu_konbini_shelf4",
        "x": 7,
        "y": 7,
        "w": 3,
        "h": 1,
        "script": "konbini_shelf"
      },
      {
        "id": "konbini_ice",
        "sprite": "fu_konbini_ice",
        "x": 2,
        "y": 8,
        "w": 2,
        "h": 1,
        "script": "konbini_ice"
      },
      {
        "id": "konbini_endcap",
        "sprite": "fu_konbini_endcap",
        "x": 9,
        "y": 8,
        "w": 1,
        "h": 1,
        "script": "konbini_shelf"
      },
      {
        "id": "konbini_fridges",
        "x": 2,
        "y": 3,
        "w": 3,
        "h": 1,
        "script": "konbini_fridge"
      },
      {
        "id": "konbini_bento",
        "x": 5,
        "y": 3,
        "w": 3,
        "h": 1,
        "script": "konbini_bento"
      },
      {
        "id": "konbini_coffee",
        "x": 10,
        "y": 3,
        "w": 1,
        "h": 1,
        "script": "konbini_coffee"
      },
      {
        "id": "konbini_rack",
        "x": 1,
        "y": 4,
        "w": 1,
        "h": 4,
        "script": "konbini_magazines"
      },
      {
        "id": "konbini_plant",
        "x": 1,
        "y": 8,
        "w": 1,
        "h": 1,
        "script": "plant"
      },
      {
        "id": "konbini_magazines",
        "x": 1,
        "y": 10,
        "w": 5,
        "h": 1,
        "script": "konbini_magazines"
      },
      {
        "id": "konbini_baskets",
        "x": 9,
        "y": 10,
        "w": 1,
        "h": 1,
        "script": "konbini_baskets"
      },
      {
        "id": "konbini_bins",
        "x": 10,
        "y": 10,
        "w": 2,
        "h": 1,
        "script": "konbini_trash"
      },
      {
        "id": "konbini_atm",
        "x": 12,
        "y": 9,
        "w": 2,
        "h": 1,
        "script": "konbini_atm"
      }
    ],
    "image": "room2_konbini"
  },
  "cafe": {
    "tiles": [
      "WWWWWWWWWWWWW",
      "WWWWWWWWWWWWW",
      "WWWWWWWWWWWWW",
      "WWWWWWWWWWWWW",
      "WcccccccccWWW",
      "WcccccccccfWW",
      "WWfffffffffWW",
      "WWffffffffffW",
      "WWffffffffffW",
      "WWfffffffffWW",
      "WWfffffffffWW",
      "WWWWWWDWWWWWW"
    ],
    "objects": [
      {
        "id": "cafe_stool1",
        "sprite": "fu_cafe_stool1",
        "x": 2,
        "y": 6,
        "w": 1,
        "h": 1,
        "script": "cafe_counter"
      },
      {
        "id": "cafe_stool2",
        "sprite": "fu_cafe_stool2",
        "x": 4,
        "y": 6,
        "w": 1,
        "h": 1,
        "script": "cafe_counter"
      },
      {
        "id": "cafe_stool3",
        "sprite": "fu_cafe_stool3",
        "x": 6,
        "y": 6,
        "w": 1,
        "h": 1,
        "script": "cafe_counter"
      },
      {
        "id": "cafe_table",
        "sprite": "fu_cafe_table",
        "x": 3,
        "y": 8,
        "w": 1,
        "h": 1,
        "script": "cafe_table"
      },
      {
        "id": "cafe_chair1",
        "sprite": "fu_cafe_chair1",
        "x": 2,
        "y": 8,
        "w": 1,
        "h": 1,
        "script": "cafe_table"
      },
      {
        "id": "cafe_chair2",
        "sprite": "fu_cafe_chair2",
        "x": 4,
        "y": 8,
        "w": 1,
        "h": 1,
        "script": "cafe_table"
      },
      {
        "id": "cafe_table2",
        "sprite": "fu_cafe_table2",
        "x": 3,
        "y": 10,
        "w": 1,
        "h": 1,
        "script": "cafe_table"
      },
      {
        "id": "cafe_chair3",
        "sprite": "fu_cafe_chair3",
        "x": 2,
        "y": 10,
        "w": 1,
        "h": 1,
        "script": "cafe_table"
      },
      {
        "id": "cafe_chair4",
        "sprite": "fu_cafe_chair4",
        "x": 4,
        "y": 10,
        "w": 1,
        "h": 1,
        "script": "cafe_table"
      },
      {
        "id": "cafe_booth_t",
        "sprite": "fu_cafe_booth_t",
        "x": 8,
        "y": 7,
        "w": 2,
        "h": 1,
        "script": "cafe_sofa"
      },
      {
        "id": "cafe_booth_table",
        "sprite": "fu_cafe_booth_table",
        "x": 8,
        "y": 8,
        "w": 2,
        "h": 1,
        "script": "cafe_table"
      },
      {
        "id": "cafe_booth_b",
        "sprite": "fu_cafe_booth_b",
        "x": 8,
        "y": 9,
        "w": 2,
        "h": 1,
        "script": "cafe_sofa"
      },
      {
        "id": "cafe_sign",
        "sprite": "fu_cafe_sign",
        "x": 7,
        "y": 10,
        "w": 1,
        "h": 1,
        "script": "cafe_menu"
      },
      {
        "id": "cafe_counter",
        "x": 1,
        "y": 4,
        "w": 9,
        "h": 2,
        "script": "cafe_counter"
      },
      {
        "id": "cafe_fridge",
        "x": 10,
        "y": 4,
        "w": 1,
        "h": 1,
        "script": "cafe_shelf"
      },
      {
        "id": "cafe_cupboard",
        "x": 11,
        "y": 4,
        "w": 1,
        "h": 2,
        "script": "cafe_shelf"
      },
      {
        "id": "cafe_clock",
        "x": 11,
        "y": 6,
        "w": 1,
        "h": 1,
        "script": "cafe_clock"
      },
      {
        "id": "cafe_books",
        "x": 1,
        "y": 6,
        "w": 1,
        "h": 5,
        "script": "cafe_books"
      },
      {
        "id": "cafe_plant",
        "x": 11,
        "y": 9,
        "w": 1,
        "h": 2,
        "script": "plant"
      }
    ],
    "image": "room2_cafe"
  },
  "apartment": {
    "tiles": [
      "WWWWWWWWWWWW",
      "WWWWWWWWWWWW",
      "WWWfWWWWWWWW",
      "WWWfWWWWWWWW",
      "WWWffWWWWWWW",
      "WWWfffffffWW",
      "WfffffffffWW",
      "WWWfffffffWW",
      "WWWWffffffWW",
      "WWWWfffffWWW",
      "WfffffffWWWW",
      "WWWWWDDWWWWW"
    ],
    "objects": [
      {
        "id": "apartment_kotatsu",
        "sprite": "fu_apartment_kotatsu",
        "x": 6,
        "y": 6,
        "w": 2,
        "h": 2,
        "script": "kotatsu"
      },
      {
        "id": "apartment_cushion_b",
        "sprite": "fu_apartment_cushion_b",
        "x": 5,
        "y": 7,
        "w": 1,
        "h": 1,
        "solid": false
      },
      {
        "id": "apartment_cushion_r",
        "sprite": "fu_apartment_cushion_r",
        "x": 8,
        "y": 7,
        "w": 1,
        "h": 1,
        "solid": false
      },
      {
        "id": "apartment_laundry",
        "sprite": "fu_apartment_laundry",
        "x": 3,
        "y": 5,
        "w": 1,
        "h": 1,
        "script": "laundry"
      },
      {
        "id": "apartment_bed",
        "x": 1,
        "y": 2,
        "w": 2,
        "h": 4,
        "script": "bed"
      },
      {
        "id": "apartment_desk",
        "x": 4,
        "y": 2,
        "w": 4,
        "h": 2,
        "script": "desk"
      },
      {
        "id": "apartment_chair",
        "x": 5,
        "y": 4,
        "w": 1,
        "h": 1,
        "script": "desk"
      },
      {
        "id": "apartment_shelf",
        "x": 8,
        "y": 2,
        "w": 1,
        "h": 3,
        "script": "shelf"
      },
      {
        "id": "apartment_wardrobe",
        "x": 9,
        "y": 2,
        "w": 2,
        "h": 3,
        "script": "wardrobe"
      },
      {
        "id": "apartment_lamp",
        "x": 10,
        "y": 5,
        "w": 1,
        "h": 1,
        "script": "floorlamp"
      },
      {
        "id": "apartment_tv",
        "x": 10,
        "y": 6,
        "w": 1,
        "h": 3,
        "script": "tv"
      },
      {
        "id": "apartment_plant",
        "x": 10,
        "y": 9,
        "w": 1,
        "h": 2,
        "script": "plant"
      },
      {
        "id": "apartment_mirror",
        "x": 9,
        "y": 9,
        "w": 1,
        "h": 2,
        "script": "mirror_room"
      },
      {
        "id": "apartment_shoes",
        "x": 8,
        "y": 10,
        "w": 1,
        "h": 1,
        "script": "shoes"
      },
      {
        "id": "apartment_kitchen",
        "x": 1,
        "y": 7,
        "w": 2,
        "h": 3,
        "script": "kitchen"
      },
      {
        "id": "apartment_fridge",
        "x": 3,
        "y": 8,
        "w": 1,
        "h": 2,
        "script": "fridge"
      }
    ],
    "image": "room2_apartment"
  },
  "library": {
    "tiles": [
      "WWWWWWWWWWWWWW",
      "WWWWWWWWWWWWWW",
      "WWWWWWWWWWWWWW",
      "WWWWWWWWWWWWWW",
      "WWffffffffffWW",
      "WWffffffffffWW",
      "WWffffffffffWW",
      "WWffffffffffWW",
      "WWffffffffffWW",
      "WWffffffffffWW",
      "WWffffffffffWW",
      "WWWWWWDDWWWWWW"
    ],
    "objects": [
      {
        "id": "library_chair1",
        "sprite": "fu_library_chair1",
        "x": 3,
        "y": 5,
        "w": 1,
        "h": 1,
        "script": "library_table"
      },
      {
        "id": "library_chair2",
        "sprite": "fu_library_chair2",
        "x": 5,
        "y": 5,
        "w": 1,
        "h": 1,
        "script": "library_table"
      },
      {
        "id": "library_table",
        "sprite": "fu_library_table",
        "x": 3,
        "y": 6,
        "w": 3,
        "h": 1,
        "script": "library_table"
      },
      {
        "id": "library_chair3",
        "sprite": "fu_library_chair3",
        "x": 3,
        "y": 7,
        "w": 1,
        "h": 1,
        "script": "library_table"
      },
      {
        "id": "library_chair4",
        "sprite": "fu_library_chair4",
        "x": 5,
        "y": 7,
        "w": 1,
        "h": 1,
        "script": "library_table"
      },
      {
        "id": "library_armchair1",
        "sprite": "fu_library_armchair1",
        "x": 7,
        "y": 5,
        "w": 1,
        "h": 1,
        "script": "library_reading"
      },
      {
        "id": "library_round",
        "sprite": "fu_library_round",
        "x": 8,
        "y": 5,
        "w": 1,
        "h": 1,
        "script": "library_reading"
      },
      {
        "id": "library_armchair2",
        "sprite": "fu_library_armchair2",
        "x": 9,
        "y": 5,
        "w": 1,
        "h": 1,
        "script": "library_reading"
      },
      {
        "id": "library_librarian_chair",
        "sprite": "fu_library_librarian_chair",
        "x": 10,
        "y": 7,
        "w": 1,
        "h": 1,
        "solid": false
      },
      {
        "id": "library_desk",
        "sprite": "fu_library_desk",
        "x": 8,
        "y": 8,
        "w": 3,
        "h": 1,
        "script": "library_desk"
      },
      {
        "id": "library_cart",
        "sprite": "fu_library_cart",
        "x": 2,
        "y": 9,
        "w": 1,
        "h": 1,
        "script": "library_cart"
      },
      {
        "id": "library_magazines",
        "sprite": "fu_library_magazines",
        "x": 11,
        "y": 4,
        "w": 1,
        "h": 1,
        "script": "library_magazines"
      },
      {
        "id": "library_shelf",
        "x": 1,
        "y": 3,
        "w": 9,
        "h": 1,
        "script": "library_shelf"
      },
      {
        "id": "library_clock",
        "x": 10,
        "y": 3,
        "w": 1,
        "h": 1,
        "script": "library_clock"
      },
      {
        "id": "library_shelf2",
        "x": 11,
        "y": 3,
        "w": 2,
        "h": 1,
        "script": "library_shelf"
      },
      {
        "id": "library_shelf3",
        "x": 1,
        "y": 4,
        "w": 1,
        "h": 2,
        "script": "library_shelf"
      },
      {
        "id": "library_globe",
        "x": 1,
        "y": 6,
        "w": 1,
        "h": 1,
        "script": "library_globe"
      },
      {
        "id": "library_shelf4",
        "x": 1,
        "y": 7,
        "w": 1,
        "h": 4,
        "script": "library_shelf"
      },
      {
        "id": "library_display",
        "x": 12,
        "y": 4,
        "w": 1,
        "h": 7,
        "script": "library_display"
      }
    ],
    "image": "room2_library"
  },
  "lab": {
    "tiles": [
      "WWWWWWWWWWWWWW",
      "WWWWWWWWWWWWWW",
      "WWWWWWWWWWWWWW",
      "WWWWWWWWWWWWWW",
      "WWWWffffffffWW",
      "WWWfffffffffWW",
      "WWWfffffffffWW",
      "WWWfffffffffWW",
      "WWWfffffffffWW",
      "WWWffffffffWWW",
      "WWWWWWDDWWWWWW"
    ],
    "objects": [
      {
        "id": "lab_table",
        "sprite": "fu_lab_table",
        "x": 5,
        "y": 6,
        "w": 3,
        "h": 2,
        "script": "lab_table"
      },
      {
        "id": "lab_chair",
        "sprite": "fu_lab_chair",
        "x": 6,
        "y": 8,
        "w": 1,
        "h": 1,
        "script": "lab_table"
      },
      {
        "id": "lab_chair2",
        "sprite": "fu_lab_chair2",
        "x": 8,
        "y": 6,
        "w": 1,
        "h": 1,
        "script": "lab_table"
      },
      {
        "id": "lab_sofa",
        "sprite": "fu_lab_sofa",
        "x": 4,
        "y": 4,
        "w": 2,
        "h": 1,
        "script": "lab_sofa"
      },
      {
        "id": "lab_cart",
        "sprite": "fu_lab_cart",
        "x": 10,
        "y": 7,
        "w": 1,
        "h": 1,
        "script": "lab_cart"
      },
      {
        "id": "lab_computer",
        "x": 1,
        "y": 4,
        "w": 2,
        "h": 3,
        "script": "lab_computer"
      },
      {
        "id": "lab_whiteboard",
        "x": 4,
        "y": 3,
        "w": 3,
        "h": 1,
        "script": "lab_whiteboard"
      },
      {
        "id": "lab_desk",
        "x": 7,
        "y": 3,
        "w": 3,
        "h": 1,
        "script": "lab_papers"
      },
      {
        "id": "lab_books",
        "x": 10,
        "y": 3,
        "w": 2,
        "h": 1,
        "script": "lab_books"
      },
      {
        "id": "lab_jars",
        "x": 12,
        "y": 4,
        "w": 1,
        "h": 3,
        "script": "lab_jars"
      },
      {
        "id": "lab_coat",
        "x": 12,
        "y": 7,
        "w": 1,
        "h": 1,
        "script": "lab_coat"
      },
      {
        "id": "lab_globe",
        "x": 1,
        "y": 7,
        "w": 2,
        "h": 2,
        "script": "lab_globe"
      },
      {
        "id": "lab_boxes",
        "x": 11,
        "y": 9,
        "w": 2,
        "h": 1,
        "script": "lab_boxes"
      }
    ],
    "image": "room2_lab"
  },
  "station": {
    "tiles": [
      "WWWWWWWWWWWWWWWWWWWWWW",
      "WWWWWWWWWWWWWWWWWWWWWW",
      "WWWWWWWWWWWWWWWWWWWWWW",
      "WWWWWWWWWWWWWWWWWWWWWW",
      "WWWWWWWWWWWWWWWWWWWWWW",
      "WWWWWWWWWWWWWWWWWWWWWW",
      "WWffffffffffffffffffWW",
      "WWffffffffffffffffffWW",
      "WWffffffffffffffffffWW",
      "WWffffffffffffffffffWW",
      "WWffffffffffffffffffWW",
      "WWffffffffffffffffffWW",
      "WWffffffffffffffffffWW",
      "WWffffffffffffffffffWW",
      "WWWWWWWWWWDDWWWWWWWWWW"
    ],
    "objects": [
      {
        "id": "station_seats1",
        "sprite": "fu_station_seats1",
        "x": 3,
        "y": 8,
        "w": 3,
        "h": 1,
        "script": "station_bench"
      },
      {
        "id": "station_stove",
        "sprite": "fu_station_stove",
        "x": 4,
        "y": 9,
        "w": 1,
        "h": 1,
        "script": "station_stove"
      },
      {
        "id": "station_seats2",
        "sprite": "fu_station_seats2",
        "x": 3,
        "y": 10,
        "w": 3,
        "h": 1,
        "script": "station_bench"
      },
      {
        "id": "station_bench1",
        "sprite": "fu_station_bench1",
        "x": 15,
        "y": 8,
        "w": 2,
        "h": 1,
        "script": "station_bench"
      },
      {
        "id": "station_table",
        "sprite": "fu_station_table",
        "x": 15,
        "y": 9,
        "w": 1,
        "h": 1,
        "script": "station_bench"
      },
      {
        "id": "station_bench2",
        "sprite": "fu_station_bench2",
        "x": 15,
        "y": 10,
        "w": 2,
        "h": 1,
        "script": "station_bench"
      },
      {
        "id": "station_board",
        "sprite": "fu_station_board",
        "x": 13,
        "y": 6,
        "w": 1,
        "h": 1,
        "script": "station_timetable"
      },
      {
        "id": "station_plant3",
        "sprite": "fu_station_plant3",
        "x": 19,
        "y": 6,
        "w": 1,
        "h": 1,
        "script": "plant"
      },
      {
        "id": "station_map",
        "x": 2,
        "y": 5,
        "w": 1,
        "h": 1,
        "script": "station_map"
      },
      {
        "id": "station_window",
        "x": 3,
        "y": 5,
        "w": 4,
        "h": 1,
        "script": "station_window"
      },
      {
        "id": "station_ticket",
        "x": 7,
        "y": 5,
        "w": 2,
        "h": 1,
        "script": "station_ticket"
      },
      {
        "id": "station_timetable",
        "x": 9,
        "y": 5,
        "w": 3,
        "h": 1,
        "script": "station_timetable"
      },
      {
        "id": "station_poster",
        "x": 12,
        "y": 5,
        "w": 1,
        "h": 1,
        "script": "station_poster"
      },
      {
        "id": "station_gate",
        "x": 14,
        "y": 5,
        "w": 6,
        "h": 1,
        "script": "station_gate"
      },
      {
        "id": "station_lockers",
        "x": 2,
        "y": 6,
        "w": 1,
        "h": 5,
        "script": "station_locker"
      },
      {
        "id": "station_plant",
        "x": 2,
        "y": 11,
        "w": 1,
        "h": 2,
        "script": "plant"
      },
      {
        "id": "station_posters",
        "x": 20,
        "y": 5,
        "w": 1,
        "h": 3,
        "script": "station_poster"
      },
      {
        "id": "station_vending",
        "x": 19,
        "y": 8,
        "w": 2,
        "h": 4,
        "script": "vending"
      },
      {
        "id": "station_plant2",
        "x": 7,
        "y": 13,
        "w": 1,
        "h": 1,
        "script": "plant"
      },
      {
        "id": "station_bin1",
        "x": 8,
        "y": 13,
        "w": 1,
        "h": 1,
        "script": "station_trash"
      },
      {
        "id": "station_bin2",
        "x": 13,
        "y": 13,
        "w": 1,
        "h": 1,
        "script": "station_trash"
      }
    ],
    "image": "room2_station"
  }
};
