import type { VocabEntry } from '../core/types';

/**
 * Chapter 1 vocabulary. Levels are approximate and based on common N2 study
 * resources — the JLPT does not publish an official vocabulary list.
 * "story" marks words needed for the plot that are above or outside N2.
 */
const V = (e: Omit<VocabEntry, 'tags' | 'chapter'> & { tags?: string[]; chapter?: number }): VocabEntry => ({
  tags: [],
  chapter: 1,
  ...e,
});

export const VOCAB: VocabEntry[] = [
  // --- moving in / daily life ---
  V({ id: 'hikkoshi', word: '引っ越し', reading: 'ひっこし', en: 'moving (house)', de: 'Umzug', pos: 'noun', level: 'N3',
    example: '引っ越しの片付けがまだ終わっていない。', exampleEn: "I still haven't finished unpacking after the move.", tags: ['life'], collocations: ['引っ越しをする', '引っ越し先'] }),
  V({ id: 'ooya', word: '大家', reading: 'おおや', en: 'landlord / landlady', de: 'Vermieter(in)', pos: 'noun', level: 'N2',
    example: '大家さんに家賃を払いに行った。', exampleEn: 'I went to pay the rent to my landlady.', tags: ['life'] }),
  V({ id: 'azukeru', word: '預ける', reading: 'あずける', en: 'to leave in (someone\'s) care, to deposit', de: 'anvertrauen, hinterlegen', pos: 'verb', level: 'N3',
    example: '鍵は管理人に預けておきます。', exampleEn: "I'll leave the key with the building manager.", tags: ['life'], collocations: ['荷物を預ける', 'お金を預ける'], related: ['azukaru'] }),
  V({ id: 'azukaru', word: '預かる', reading: 'あずかる', en: 'to look after, to keep (for someone)', de: 'in Verwahrung nehmen', pos: 'verb', level: 'N2',
    example: 'お客様のお荷物をお預かりします。', exampleEn: "We'll look after your luggage.", tags: ['life', 'keigo'], related: ['azukeru'] }),
  V({ id: 'kanrinin', word: '管理人', reading: 'かんりにん', en: 'building manager, caretaker', de: 'Hausverwalter(in)', pos: 'noun', level: 'N2',
    example: '困ったことがあれば、管理人に相談してください。', exampleEn: 'If you have any problems, please talk to the building manager.', tags: ['life'] }),
  V({ id: 'bunbetsu', word: '分別', reading: 'ぶんべつ', en: 'sorting (of garbage)', de: 'Mülltrennung, Sortierung', pos: 'noun', level: 'N2',
    example: 'ゴミはきちんと分別してから出してください。', exampleEn: 'Please sort your garbage properly before putting it out.', tags: ['life'] }),
  V({ id: 'shuushuu', word: '収集', reading: 'しゅうしゅう', en: 'collection (e.g. of garbage)', de: 'Abholung, Sammlung', pos: 'noun', level: 'N2',
    example: '燃えるゴミの収集日は月曜日と木曜日です。', exampleEn: 'Burnable garbage is collected on Mondays and Thursdays.', tags: ['life'] }),
  V({ id: 'keijiban', word: '掲示板', reading: 'けいじばん', en: 'bulletin board', de: 'Anschlagbrett', pos: 'noun', level: 'N2',
    example: '詳しいことは駅の掲示板に貼ってあります。', exampleEn: 'The details are posted on the bulletin board at the station.', tags: ['town'] }),
  V({ id: 'shimekiri', word: '締め切り', reading: 'しめきり', en: 'deadline', de: 'Frist, Abgabetermin', pos: 'noun', level: 'N2',
    example: 'レポートの締め切りは明日の正午だ。', exampleEn: 'The report deadline is tomorrow at noon.', tags: ['work'] }),
  V({ id: 'enryo', word: '遠慮', reading: 'えんりょ', en: 'reserve, holding back', de: 'Zurückhaltung', pos: 'noun', level: 'N3',
    example: '遠慮しないで、どんどん食べてね。', exampleEn: "Don't hold back — help yourself!", tags: ['social'], collocations: ['遠慮なく', 'ご遠慮ください'] }),
  V({ id: 'otagaisama', word: 'お互い様', reading: 'おたがいさま', en: "we're in the same boat; it goes both ways", de: 'Das beruht auf Gegenseitigkeit', pos: 'expression', level: 'N2',
    example: '困ったときはお互い様ですよ。', exampleEn: 'We all need help sometimes — that goes both ways.', tags: ['social'] }),
  V({ id: 'sasuga', word: 'さすが', reading: 'さすが', en: 'as expected (of), truly', de: 'wie zu erwarten, wirklich', pos: 'adverb', level: 'N2',
    example: 'さすが先生、何でも知っていますね。', exampleEn: 'As expected of you, sensei — you know everything.', tags: ['social'] }),
  V({ id: 'sasayaka', word: 'ささやか', reading: 'ささやか', en: 'modest, small', de: 'bescheiden, klein', pos: 'na-adj', level: 'N2',
    example: 'ささやかですが、お礼の気持ちです。', exampleEn: "It's only something small, but it's a token of my thanks.", tags: ['social'] }),

  // --- convenience store ---
  V({ id: 'shinagire', word: '品切れ', reading: 'しなぎれ', en: 'out of stock, sold out', de: 'ausverkauft', pos: 'noun', level: 'N2',
    example: 'その商品はただいま品切れとなっております。', exampleEn: 'That product is currently out of stock.', tags: ['shop'], related: ['zaiko'] }),
  V({ id: 'zaiko', word: '在庫', reading: 'ざいこ', en: 'stock, inventory', de: 'Lagerbestand', pos: 'noun', level: 'N2',
    example: '在庫を確認してまいります。', exampleEn: "I'll go and check our stock.", tags: ['shop'], related: ['shinagire'] }),
  V({ id: 'toriyoseru', word: '取り寄せる', reading: 'とりよせる', en: 'to order in, to have sent', de: 'bestellen, kommen lassen', pos: 'verb', level: 'N2',
    example: '在庫がないので、メーカーから取り寄せます。', exampleEn: "It's not in stock, so we'll order it from the manufacturer.", tags: ['shop'] }),
  V({ id: 'ryoushuusho', word: '領収書', reading: 'りょうしゅうしょ', en: 'receipt (formal)', de: 'Quittung', pos: 'noun', level: 'N2',
    example: '領収書をいただけますか。', exampleEn: 'Could I have a receipt, please?', tags: ['shop'] }),
  V({ id: 'jouren', word: '常連', reading: 'じょうれん', en: 'regular customer', de: 'Stammkunde', pos: 'noun', level: 'N2',
    example: 'あの人はこの店の常連だ。', exampleEn: "That person is a regular at this shop.", tags: ['shop'] }),
  V({ id: 'shoumikigen', word: '賞味期限', reading: 'しょうみきげん', en: 'best-before date', de: 'Mindesthaltbarkeitsdatum', pos: 'noun', level: 'N2',
    example: 'このパンは賞味期限が切れている。', exampleEn: 'This bread is past its best-before date.', tags: ['shop'] }),
  V({ id: 'osoreiru', word: '恐れ入ります', reading: 'おそれいります', en: "I'm sorry to trouble you; thank you (very polite)", de: 'Verzeihung / vielen Dank (sehr höflich)', pos: 'expression', level: 'N2',
    example: '恐れ入りますが、少々お待ちください。', exampleEn: "I'm sorry, but could you please wait a moment?", tags: ['keigo'] }),
  V({ id: 'shouchi', word: '承知', reading: 'しょうち', en: 'understanding, consent', de: 'Einverständnis, Kenntnisnahme', pos: 'noun', level: 'N2',
    example: '承知いたしました。すぐに準備します。', exampleEn: 'Understood. I will prepare it right away.', tags: ['keigo'], collocations: ['承知しました', 'ご承知のとおり'] }),

  // --- mystery / letters ---
  V({ id: 'sashidashinin', word: '差出人', reading: 'さしだしにん', en: 'sender (of a letter)', de: 'Absender', pos: 'noun', level: 'N2',
    example: '差出人の名前が書かれていない手紙が届いた。', exampleEn: 'A letter arrived with no sender name on it.', tags: ['mystery'], related: ['atesaki'] }),
  V({ id: 'atesaki', word: '宛先', reading: 'あてさき', en: 'address, addressee', de: 'Empfänger(adresse)', pos: 'noun', level: 'N2',
    example: 'メールの宛先を間違えてしまった。', exampleEn: 'I sent the email to the wrong address.', tags: ['mystery'], related: ['sashidashinin'] }),
  V({ id: 'tegakari', word: '手がかり', reading: 'てがかり', en: 'clue, lead', de: 'Hinweis, Anhaltspunkt', pos: 'noun', level: 'N2',
    example: '事件の手がかりがようやく見つかった。', exampleEn: 'A clue to the case was finally found.', tags: ['mystery'] }),
  V({ id: 'nazo', word: '謎', reading: 'なぞ', en: 'mystery, riddle', de: 'Rätsel', pos: 'noun', level: 'N2',
    example: 'その事件は今も謎に包まれている。', exampleEn: 'That incident is still shrouded in mystery.', tags: ['mystery'] }),
  V({ id: 'kehai', word: '気配', reading: 'けはい', en: 'sign, presence, indication', de: 'Anzeichen, Anwesenheit', pos: 'noun', level: 'N2',
    example: '後ろに誰かがいる気配がした。', exampleEn: 'I sensed someone behind me.', tags: ['mystery'] }),
  V({ id: 'mimiwosumasu', word: '耳を澄ます', reading: 'みみをすます', en: 'to listen carefully, to strain one\'s ears', de: 'genau hinhören', pos: 'expression', level: 'N2',
    example: '耳を澄ますと、川の音が聞こえる。', exampleEn: 'If you listen carefully, you can hear the river.', tags: ['mystery'] }),
  V({ id: 'aimai', word: '曖昧', reading: 'あいまい', en: 'vague, ambiguous', de: 'vage, unklar', pos: 'na-adj', level: 'N2',
    example: '彼はいつも曖昧な返事をする。', exampleEn: 'He always gives vague answers.', tags: ['social'] }),
  V({ id: 'tomadou', word: '戸惑う', reading: 'とまどう', en: 'to be bewildered, to be at a loss', de: 'verwirrt sein', pos: 'verb', level: 'N2',
    example: '急に話しかけられて、戸惑ってしまった。', exampleEn: 'I was taken aback when someone suddenly spoke to me.', tags: ['emotion'] }),
  V({ id: 'awateru', word: '慌てる', reading: 'あわてる', en: 'to panic, to be flustered', de: 'in Panik geraten, hektisch werden', pos: 'verb', level: 'N2',
    example: '慌てなくても大丈夫。まだ時間はあるよ。', exampleEn: "No need to panic. There's still time.", tags: ['emotion'] }),
  V({ id: 'iiwake', word: '言い訳', reading: 'いいわけ', en: 'excuse, justification', de: 'Ausrede', pos: 'noun', level: 'N2',
    example: '遅刻した理由について、彼は言い訳ばかりしていた。', exampleEn: 'He kept making excuses about why he was late.', tags: ['social'] }),

  // --- station ---
  V({ id: 'kaisatsu', word: '改札', reading: 'かいさつ', en: 'ticket gate', de: 'Fahrkartensperre', pos: 'noun', level: 'N2',
    example: '改札の前で待ち合わせしよう。', exampleEn: "Let's meet in front of the ticket gates.", tags: ['station'] }),
  V({ id: 'chien', word: '遅延', reading: 'ちえん', en: 'delay', de: 'Verspätung', pos: 'noun', level: 'N2',
    example: '信号トラブルの影響で、電車に遅延が出ています。', exampleEn: 'Trains are delayed due to a signal problem.', tags: ['station'] }),
  V({ id: 'eikyou', word: '影響', reading: 'えいきょう', en: 'influence, effect', de: 'Einfluss, Auswirkung', pos: 'noun', level: 'N3',
    example: '台風の影響で、多くの便が欠航になった。', exampleEn: 'Many flights were cancelled because of the typhoon.', tags: ['station'] }),
  V({ id: 'saikai', word: '再開', reading: 'さいかい', en: 'resumption', de: 'Wiederaufnahme', pos: 'noun', level: 'N2',
    example: '運転の再開は十時半ごろの見込みです。', exampleEn: 'Service is expected to resume around 10:30.', tags: ['station'] }),
  V({ id: 'miawase', word: '見合わせ', reading: 'みあわせ', en: 'suspension, postponement', de: 'vorläufige Einstellung', pos: 'noun', level: 'N2',
    example: '強風のため、運転を見合わせています。', exampleEn: 'Service is suspended due to strong winds.', tags: ['station'] }),
  V({ id: 'norikae', word: '乗り換え', reading: 'のりかえ', en: 'transfer (trains)', de: 'Umsteigen', pos: 'noun', level: 'N3',
    example: '次の駅で乗り換えてください。', exampleEn: 'Please change trains at the next station.', tags: ['station'] }),
  V({ id: 'meiwaku', word: '迷惑', reading: 'めいわく', en: 'trouble, inconvenience', de: 'Belästigung, Unannehmlichkeit', pos: 'noun', level: 'N3',
    example: 'ご迷惑をおかけして、申し訳ございません。', exampleEn: 'We sincerely apologise for the inconvenience.', tags: ['keigo'] }),

  // --- research / memory ---
  V({ id: 'kioku', word: '記憶', reading: 'きおく', en: 'memory', de: 'Erinnerung, Gedächtnis', pos: 'noun', level: 'N2',
    example: '子供の頃の記憶はほとんど残っていない。', exampleEn: 'I have almost no memories of my childhood.', tags: ['memory'] }),
  V({ id: 'usureru', word: '薄れる', reading: 'うすれる', en: 'to fade, to grow faint', de: 'verblassen', pos: 'verb', level: 'N2',
    example: '時間がたつにつれて、記憶が薄れていく。', exampleEn: 'As time passes, memories fade.', tags: ['memory'] }),
  V({ id: 'yomigaeru', word: '蘇る', reading: 'よみがえる', en: 'to be revived, to come back (memories)', de: 'wiederaufleben', pos: 'verb', level: 'N1',
    example: 'その歌を聞くと、子供の頃の記憶が蘇る。', exampleEn: 'When I hear that song, childhood memories come back.', tags: ['memory'] }),
  V({ id: 'ushinau', word: '失う', reading: 'うしなう', en: 'to lose', de: 'verlieren', pos: 'verb', level: 'N2',
    example: '彼は事故で記憶を失った。', exampleEn: 'He lost his memory in an accident.', tags: ['memory'] }),
  V({ id: 'genshou', word: '現象', reading: 'げんしょう', en: 'phenomenon', de: 'Phänomen', pos: 'noun', level: 'N2',
    example: 'この現象はまだ科学的に説明されていない。', exampleEn: 'This phenomenon has not yet been explained scientifically.', tags: ['research'] }),
  V({ id: 'chousa', word: '調査', reading: 'ちょうさ', en: 'investigation, survey', de: 'Untersuchung', pos: 'noun', level: 'N2',
    example: '原因について、現在調査を進めています。', exampleEn: 'We are currently investigating the cause.', tags: ['research'] }),
  V({ id: 'kenkyuujo', word: '研究所', reading: 'けんきゅうじょ', en: 'research institute', de: 'Forschungsinstitut', pos: 'noun', level: 'N2',
    example: '町の外れに古い研究所がある。', exampleEn: 'There is an old research institute on the edge of town.', tags: ['research'] }),
  V({ id: 'tachiirikinshi', word: '立入禁止', reading: 'たちいりきんし', en: 'no entry', de: 'Betreten verboten', pos: 'noun', level: 'N2',
    example: 'この先は工事中のため立入禁止です。', exampleEn: 'No entry beyond this point due to construction.', tags: ['research'] }),
  V({ id: 'tanomoshii', word: '頼もしい', reading: 'たのもしい', en: 'reliable, promising', de: 'zuverlässig, vielversprechend', pos: 'i-adj', level: 'N2',
    example: '新しい仲間がいて、頼もしいかぎりだ。', exampleEn: "Having a new companion is truly reassuring.", tags: ['social'] }),

  // --- forest / shrine ---
  V({ id: 'shigemi', word: '茂み', reading: 'しげみ', en: 'thicket, bushes', de: 'Gebüsch, Dickicht', pos: 'noun', level: 'N1',
    example: '茂みの中から小さな動物が飛び出してきた。', exampleEn: 'A small animal jumped out of the bushes.', tags: ['nature'] }),
  V({ id: 'ashiato', word: '足跡', reading: 'あしあと', en: 'footprint(s)', de: 'Fußspur', pos: 'noun', level: 'N2',
    example: '雪の上に小さな足跡が残っていた。', exampleEn: 'Small footprints were left in the snow.', tags: ['nature'] }),
  V({ id: 'kizamu', word: '刻む', reading: 'きざむ', en: 'to carve, to engrave; to chop', de: 'einritzen, eingravieren; hacken', pos: 'verb', level: 'N2',
    example: '石に古い文字が刻まれている。', exampleEn: 'Old characters are carved into the stone.', tags: ['nature'] }),
  V({ id: 'kakera', word: '欠片', reading: 'かけら', en: 'fragment, shard', de: 'Bruchstück, Splitter', pos: 'noun', level: 'story',
    example: '割れたガラスの欠片に気をつけて。', exampleEn: 'Watch out for the shards of broken glass.', tags: ['story'] }),
  V({ id: 'kotodama', word: '言霊', reading: 'ことだま', en: 'spirit of words (word-soul)', de: 'Wortgeist', pos: 'noun', level: 'story',
    example: '日本では昔から、言葉には言霊が宿ると言われている。', exampleEn: 'In Japan it has long been said that a spirit dwells in words.', tags: ['story'] }),
  V({ id: 'sanpai', word: '参拝', reading: 'さんぱい', en: 'visit to a shrine/temple (to pray)', de: 'Schrein-/Tempelbesuch', pos: 'noun', level: 'N2',
    example: '初詣で神社に参拝した。', exampleEn: 'I visited the shrine for the first prayer of the year.', tags: ['culture'] }),
  V({ id: 'natsukashii', word: '懐かしい', reading: 'なつかしい', en: 'nostalgic, dear (old)', de: 'nostalgisch, vertraut', pos: 'i-adj', level: 'N3',
    example: 'この写真、懐かしいね。', exampleEn: 'This photo brings back memories, doesn\'t it?', tags: ['memory'] }),
  V({ id: 'happyou', word: '発表', reading: 'はっぴょう', en: 'presentation, announcement', de: 'Präsentation, Bekanntgabe', pos: 'noun', level: 'N3',
    example: '来週、ゼミで研究の発表をする。', exampleEn: 'Next week I will present my research in the seminar.', tags: ['university'] }),
  V({ id: 'kinchou', word: '緊張', reading: 'きんちょう', en: 'nervousness, tension', de: 'Nervosität, Anspannung', pos: 'noun', level: 'N3',
    example: '人前で話すと、どうしても緊張してしまう。', exampleEn: "I can't help getting nervous when I speak in front of people.", tags: ['university', 'emotion'] }),
];

export const VOCAB_BY_ID: Record<string, VocabEntry> = Object.fromEntries(VOCAB.map((v) => [v.id, v]));
