"""
Painted ground for the outdoor maps.
Town: art/sheets/ground_town_draft.webp scaled to the 44 x 30 town grid -> public/assets/map_town.png
(the town grid in src/content/maps.ts was adjusted to the picture by hand).
Midori Forest: art/sheets/ground_forest_draft.webp (30 x 26 tiles) -> public/assets/map_forest.png
and src/content/forest.gen.ts (the collision / terrain grid).
The grid was read off the picture: T forest wall, " tall grass (encounters), : path, K cliff,
H stairs, ~ pond, . grass.

Run: python3 tools/build_ground.py
"""
import json
import os
from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
W, H, T = 30, 26, 32

g = [['.'] * W for _ in range(H)]


def rect(ch, x0, y0, x1, y1):
    for y in range(y0, y1 + 1):
        for x in range(x0, x1 + 1):
            g[y][x] = ch


# forest wall around the clearing
rect('T', 0, 0, 29, 1)
rect('T', 0, 0, 0, 25)
rect('T', 29, 0, 29, 25)
rect('T', 0, 23, 29, 25)
rect('T', 1, 22, 1, 22)
# tall grass patches
rect('"', 2, 8, 9, 12)
rect('"', 15, 6, 19, 9)
rect('"', 21, 3, 27, 5)
rect('"', 21, 6, 22, 12)
rect('"', 24, 10, 27, 12)
rect('"', 2, 17, 8, 21)
rect('"', 16, 18, 22, 21)
rect('"', 20, 16, 27, 17)
# path from the top clearing down to the cliff stairs
rect(':', 14, 0, 15, 1)
rect(':', 14, 4, 15, 6)
rect(':', 12, 7, 14, 10)
rect(':', 12, 10, 19, 11)
rect(':', 18, 11, 19, 12)
# cliff ledge with stairs
rect('K', 1, 13, 28, 14)
rect('H', 18, 13, 19, 14)
# path below the cliff to the south exit
rect(':', 18, 15, 19, 17)
rect(':', 10, 16, 19, 17)
rect(':', 10, 17, 11, 21)
rect(':', 10, 20, 15, 21)
rect(':', 14, 21, 15, 25)
# pond
rect('~', 23, 18, 27, 22)

rows = [''.join(r) for r in g]
src = Image.open(os.path.join(ROOT, 'art', 'sheets', 'ground_forest_draft.webp')).convert('RGB')
src.resize((W * T, H * T), Image.LANCZOS).save(os.path.join(ROOT, 'public', 'assets', 'map_forest.png'))
ts = '/* generated by tools/build_ground.py — do not edit */\nexport const FOREST_GEN: string[] = ' + json.dumps(rows, indent=2) + ';\n'
open(os.path.join(ROOT, 'src', 'content', 'forest.gen.ts'), 'w').write(ts)
town = Image.open(os.path.join(ROOT, 'art', 'sheets', 'ground_town_draft.webp')).convert('RGB')
town.resize((44 * T, 30 * T), Image.LANCZOS).save(os.path.join(ROOT, 'public', 'assets', 'map_town.png'))
print('\n'.join(rows))
